apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-deployment
  labels:
    app: animals
spec:
  replicas: 6
  selector:
    matchLabels:
      app: animals
  template:
    metadata:
      labels:
        app: animals
    spec:
      containers:
      - name: animals
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: animals-svc
spec:
  type: LoadBalancer
  selector:
    app: animals
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
